name: Setup, assess code format and test

on: [ push, pull_request ]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          PINECONE_ENV: ${{ secrets.PINECONE_ENV }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}

      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

  assess_code_format:
      needs: setup
      runs-on: ubuntu-latest
      steps:
        - name: Code quality checks
          run: |
            isort --check-only .
            black --check .
            ruff check .

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test with pytest
        run: |
          python -m pytest
